### ISSUE TITLE
Doesn't run on base craftos2 emulator

### ISSUE THREAD

**Issue by RGFTheCoder** [MCJack123/CCKernel2#4]
Trying to run the program on CraftOS-PC v2.5.3 crashes in init.lua
```
CraftOS-PC v2.5.3
Built with: cli png mixer print_pdf
Copyright (c) 2019-2021 JackMacWindows. Licensed under the MIT License.
```
Log:
![Screenshot_20210325_215210](https://user-images.githubusercontent.com/24970643/112565888-5be07b00-8db4-11eb-9dbf-d166c99ac148.png)
More error info that appears in GUI mode:
![Screenshot_20210325_215236](https://user-images.githubusercontent.com/24970643/112565976-8a5e5600-8db4-11eb-8b06-e840c5af8175.png)
![Screenshot_20210325_215241](https://user-images.githubusercontent.com/24970643/112565977-8a5e5600-8db4-11eb-8a70-2513c2b44355.png)
![Screenshot_20210325_215254](https://user-images.githubusercontent.com/24970643/112565978-8a5e5600-8db4-11eb-9ccc-8b1f7bb00bd4.png)

**Comment by MCJack123** [comment]
I think I've seen this issue, but I don't remember what the fix is. This project is abandoned, and it shouldn't really be used anymore, especially due to the number of hacks I put in it. I've got something in the works to replace it, but for now you're on your own.
